### ISSUE TITLE
Subnetting

### ISSUE THREAD

**Issue by DancinParrot** [projectcatena/cloudlabs-server#34]
Instances should not be public and should not have public IP address, as vulnerable machines can be attacked

Segment VMs according to modules, don't want machines to have public IP adress

~Should have a way of VPNing into GCP and access the VMs~
~Might not need VPN, as guac is hosted within VPC, so should be able to access the VMs, but need to configure routing.~
No need VPN

**Comment by DancinParrot** [comment]
We need these 3 firewall rules to allow machines to communicate with each other within the same subnet, and across different subnets.

Basically, all traffic is blocked by default within the VPC, both intra and inter.

![Image](https://github.com/projectcatena/cloudlabs-server/assets/63692048/0f48f0a8-6c5f-4794-bc00-c7b3266db42e)

**Comment by DancinParrot** [comment]
Using GCP Java Client Library to programmatically insert a resource:

Insert Subnet resource:

- https://cloud.google.com/java/docs/reference/google-cloud-compute/latest/com.google.cloud.compute.v1.InsertSubnetworkRequest.Builder#com_google_cloud_compute_v1_InsertSubnetworkRequest_Builder_setSubnetworkResource_com_google_cloud_compute_v1_Subnetwork_
- https://cloud.google.com/java/docs/reference/google-cloud-compute/latest/com.google.cloud.compute.v1.Subnetwork.Builder

Firewall Rules:
- https://cloud.google.com/java/docs/reference/google-cloud-compute/latest/com.google.cloud.compute.v1.FirewallPolicyRule.Builder
- https://cloud.google.com/java/docs/reference/google-cloud-compute/latest/com.google.cloud.compute.v1.InsertFirewallPolicyRequest.Builder
- https://cloud.google.com/firewall/docs/using-firewalls#gcloud_5

**Comment by DancinParrot** [comment]
Allocating subnets


![Image](https://github.com/projectcatena/cloudlabs-server/assets/63692048/2e8cabba-1ccf-4835-8815-fa54d8827c15)

Consider using /28 subnet mask such that will have extra 16 subnets, such that each subnet will only have 2^4 = 16 - 2 (broadcast and network addr) - 1 (gcp gateway) = 13 hosts to work with.

**Comment by s10219129** [comment]
- [ ] Create Subnet on existing VPC
- [ ] Delete Subnet on existing VPC
- [ ] List Subnets on existing VPC
- [ ] Create Compute Instance with subnet

**Comment by DancinParrot** [comment]
Firewall Rules Creation:

- [ ] Create rule when subnet is created
- [ ] Delete rule when subnet is deleted

Rules should be automatically created/deleted to allow intrasubnet communication, as communication between hosts within the same subnet is blocked by default.
